client_config_backend: settings
client_config:
client_id: 649749258083-kguuu1srmbr99jnk84ugr9bqq4sp8ujk.apps.googleusercontent.com
client_secret: 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
save_credentials_backend: file
save_credentials_file: credentials.jsonget_refresh_token: Trueoauth_scope:
- https://www.googleapis.com/auth/drive.file